### ISSUE TITLE
How to modify dart code?

### ISSUE THREAD

**Issue by xingchenxuanfeng** [thebuggycoder/flutterstudio#3]
After generating the dart code，how can I modify the dart code?

**Comment by bytesizedwizard** [comment]
First of all, apologies for the late response.

Modifications to dart code are not supported in the current version of the project, as the app does not act as a full fledged flutter emulator yet, it might be added in the future.

Meanwhile, if you are able to work on it and submit a PR, I'll be happy to merge! Cheers!
