### ISSUE TITLE
Add Widgets EnsureInitialized

### ISSUE THREAD

**Issue by gx14ac** [thebuggycoder/flutterstudio#4]
## What
- You need to explicitly require `WidgetsFlutterBinding.ensureInitialized ()`

**Comment by gx14ac** [comment]
@siddharthpatankar hi! my name is flekystyley from japan.
I want to send a PR, please allow access

**Comment by bytesizedwizard** [comment]
Hi @flekystyley . You can fork the repo and directly submit a PR. I'll merge it if everything looks good!
Let me know if you face any issues while submitting the PR.

Closing this for now.

**Comment by gx14ac** [comment]
okay, thank you!!
I think this project will be interesting.
Please do your best
